# .github/workflows/deploy-be.yml
name: Deploy BE to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # JDK 세팅 & Gradle 빌드
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Build JAR with Gradle
      run: ./gradlew build -x test --no-daemon

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    # ECR 로그인
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
        | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    # Docker 이미지 빌드 & 푸시
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} .
        docker push  ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

  
    # EC2에 접속해 컨테이너 재시작
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.INSTANCE_HOST }}
        username: ubuntu
        key: ${{ secrets.INSTANCE_SSH_KEY }} 
        script: |
          # EC2 내부에서 ECR 인증
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

          # 컨테이너 재시작
          docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          docker stop backend || true && docker rm backend || true
          docker run -d --name backend -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=prod \
            --env SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            --env SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            --env SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            --env KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
            --env KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
            --env DEV_KAKAO_REDIRECT_URL=${{ secrets.DEV_KAKAO_REDIRECT_URL }} \
            --env PROD_KAKAO_REDIRECT_URL=${{ secrets.PROD_KAKAO_REDIRECT_URL }} \
            --env FRONTEND_REDIRECT_URL_LOCAL=${{ secrets.FRONTEND_REDIRECT_URL_LOCAL }} \
            --env FRONTEND_REDIRECT_URL_PROD=${{ secrets.FRONTEND_REDIRECT_URL_PROD }} \
            --env JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
